project:
  type: website
  output-dir: docs

website:
  title: "Jack Leary"
  repo-url: https://github.com/jr-leary7/quarto-site
  repo-actions: [edit, issue]
  repo-subdir: docs
  reader-mode: true
  twitter-card:
    creator: "@leary_jack"
    site: "@UF"
  open-graph: true
  navbar:
    search: true
    left:
      - index.qmd
      - about.qmd

format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    toc: true



