project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "tutorials/*qmd"
    - "derivations/*qmd"
    - "knowledge_base/*qmd"
    - "!tutorials/Scaffold_Simulation.qmd"
    - "!tutorials/GLMM_Benchmarking.qmd"

website:
  title: "Jack Leary"
  repo-url: https://github.com/jr-leary7/quarto-site
  repo-actions: [edit, issue]
  repo-subdir: docs
  reader-mode: true
  twitter-card:
    creator: "@leary_jack"
    site: "@UF"
  open-graph: true
  google-analytics: "G-H2832QJGSY"
  page-navigation: true
  navbar:
    search: true
    left:
      - index.qmd
      - about.qmd
      - text: "Tutorials"
        menu: 
          - tutorials/scLANE_Trajectory_DE.qmd
          - tutorials/CellRank_Tutorial.qmd
          - tutorials/SCISSORS_Reclustering.qmd
          - tutorials/GEE_Benchmarking.qmd
          - tutorials/Seurat_AnnData_Conversion.qmd
      - text: "Derivations"
        menu:
          - derivations/Intercept_Interpretation.qmd
          - derivations/Large_Sample_Practice.qmd
      - text: "Knowledge Base"
        menu: 
          - knowledge_base/scRNAseq.qmd
          - knowledge_base/R_Development.qmd

format:
  html:
    theme:
      light: minty
      dark: darkly
    toc: true
