project:
  type: website
  output-dir: docs

website:
  title: "Jack Leary"
  repo-url: https://github.com/jr-leary7/quarto-site
  repo-actions: [edit, issue]
  repo-subdir: docs
  reader-mode: true
  navbar:
    search: true
    left:
      - icon: github
        href: https://github.com/jr-leary7
      - icon: twitter 
        href: https://twitter.com/leary_jack
      - index.qmd
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



