project:
  type: website
  output-dir: docs

website:
  title: "Jack Leary"
  repo-url: https://github.com/jr-leary7/quarto-site
  repo-actions: [edit, issue]
  repo-subdir: docs
  reader-mode: true
  twitter-card:
    creator: "@leary_jack"
    site: "@UF"
  open-graph: true
  page-navigation: true
  navbar:
    search: true
    left:
      - index.qmd
      - about.qmd
      - text: "Tutorials"
        menu: 
          - tutorials/SCISSORS_Reclustering.qmd
          - tutorials/scLANE_Trajectory_DE.qmd
      - text: "Derivations"
        menu:
          - derivations/Intercept_Interpretation.qmd
      - text: "Knowledge Base"
        menu: 
          - knowledge_base/scRNAseq.qmd
          - knowledge_base/R_Development.qmd

format:
  html:
    theme:
      light: minty
      dark: darkly
    toc: true
