---
title: "Background"
---

## Education 

My undergrad degree is in statistics, which I did at the University of North Carolina at Chapel Hill (Go Heels!). After graduating in 2020, I spent some of the next two years earning a master's degree in biostatistics from the University of Florida. During my second year in that program, I applied to PhD programs and ended up deciding to continue at UF and do a PhD in the same department. I'm currently entering the second semester of my first year. My most relevant studies include courses on generalized linear models, statistical learning theory, convex optimization, probability theory, mathematical statistics, and statistical computing at the undergraduate and graduate levels. 

## Work Experience 

In the summer after my junior year at UNC, I joined [Dr. Jen Jen Yeh's lab](https://unclineberger.org/yehlab) at Lineberger Comprehensive Cancer Center. There I learned how to process and analyze genomic and transcriptomic data, and in Fall 2019 started focusing on developing methods for scRNA-seq analysis. My primary contribution there was the development of reproducible bioinformatics pipelines for bulk & single cell RNA-seq, ChIP-seq, and whole genome & exome sample processing. In addition, I developed a robust, evidence-based downstream analysis workflow for the lab's scRNA-seq samples. 

After leaving the Yeh Lab in July 2020, I moved to Jacksonville and started working full-time as a junior data analyst at Blue Cross Blue Shield of Florida. While there, I completed a year-long rotational program during which I applied regression and clustering methods to several complex business problems. A highlight was my usage of graph-based clustering and dimension reduction algorithms (concepts lifted directly from my experience with scRNA-seq data) to identify well-performing subsets of specialist doctors. After my rotations ended, I became a full analyst and spent the next year working in care analytics, where I tested and deployed machine learning algorithms used to identify people to be targeted for various preventive healthcare programs. During this time, I also completed a manuscript started while I was at the Yeh Lab detailing a method for improved clustering of single cell data containing rare cell types. 

While all this was going on, I also started doing research work (once again focused on scRNA-seq method development) in [Dr. Rhonda Bacher's group](https://www.rhondabacher.com) at UF. Our original focus was in profiling, testing, and improving existing methods for RNA velocity and trajectory inference through simulations and analysis of publicly available single cell datasets. 

After two years at Blue Cross, and graduating with my master's in May of 2022, I decided to join Dr. Bacher as a PhD student in Fall 2022. My first semester was spent pursuing scRNA-seq research, with a focus on improving the interpretability of trajectory differential expression methods. I also provided downstream analysis of single cell data generated by [Dr. Phillip Efron's lab](https://scirc.med.ufl.edu/category/philip-efron/) containing different types of peripheral blood mononuclear cells. In addition, I was the instructor for the online section of PHC 6790 (Biostatistical Computing with SAS), a master's-level course developed by fellow Tar Heel [Dr. John Kairalla](https://biostat.ufl.edu/profile/kairalla-john/). 

## Personal Interests 

Outside of research, I enjoy reading (my favorite genres are nautical adventure, weird history, and narrative science), riding my bike, cooking for my friends, and rock climbing. 

## Publications 

1. **Jack R. Leary**, Yi Xu, Ashley Morrison, Chong Jin, Emily C. Shen, Ye Su, Naim U. Rashid, Jen Jen Yeh, Xianlu Laura Peng. [Sub-cluster identification through semi-supervised optimization of rare-cell silhouettes (SCISSORS) in single-cell sequencing](https://doi.org/10.1101/2021.10.29.466448). *BioRxiv.* 466448, (2021). 

2. Matthew E. Berginski, Madison R. Jenner, Chinmaya U. Joisa, Silvia G.Herrera Loeza, Brian T. Golitz, Matthew B. Lipner, **Jack R. Leary**, Naim U. Rashid, Gary L. Johnson, Jen Jen Yeh, Shawn M. Gomez. [Kinome state is predictive of cell viability in pancreatic cancer tumor and stroma cell lines](https://doi.org/10.1101/2021.07.21.451515). *BioRxiv.* 451515, (2021). 
